networks:
  postgres_postgres:
    external: true

services:
  psql:
    image: 479190002620.dkr.ecr.ap-south-1.amazonaws.com/homelab/postgres:18
    shm_size: 1gb
    networks:
      - postgres_postgres
    volumes:
      - ~/.psqlrc:/etc/postgresql-common/.psqlrc:ro
      - /tmp/sql:/tmp/sql:ro
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  pgloader:
    image: dimitri/pgloader:v3.6.7
    networks:
      - postgres_postgres
