services:
  terraform:
    image: hashicorp/terraform:1.16.2
    working_dir: /workspace
    entrypoint:
      - "terraform"
    volumes:
      - ${PWD}:/workspace
      - ${HOME}/.aws:/.aws:ro
    environment:
      AWS_SHARED_CREDENTIALS_FILE: /.aws/credentials
      AWS_CONFIG_FILE: /.aws/config
      AWS_PROFILE: ${AWS_PROFILE:-default}
