alias wecoachdb="psql --host wecoach.cpq82ioic0rr.ap-south-1.rds.amazonaws.com --port 5432 --user postgres --dbname postgres --password"
alias cna="npx create-next-app --typescript --tailwind --eslint --app --use-yarn"
alias yd="yarn lint && yarn format && yarn build && yarn dev"
alias h="microk8s helm"
alias k="microk8s kubectl"
alias icat="kitten icat"
alias diff="kitten diff"
alias n8n="docker container run --interactive --tty --rm --name n8n --publish 5678:5678 --env GENERIC_TIMEZONE=Asia/Kolkata --env TZ=Asia/Kolkata --env N8N_ENFORCE_SETTINGS_FILE_PERMISSION=true --env N8N_RUNNERS_ENABLED=true --volume n8n_data:/home/node/.n8n docker.n8n.io/n8nio/n8n"
alias siril="/usr/local/bin/Siril-1.4.3-x86_64.AppImage"
alias graxpert="/usr/local/bin/GraXpert-linux/GraXpert"
alias autostakkert="wine /usr/local/bin/AutoStakkert_4.0.11_x64/AutoStakkert.exe"
alias dss="/opt/DeepSkyStacker/DeepSkyStacker"
alias terraform="docker compose run --rm terraform"

# PostgreSQL aliases
alias psql="docker compose --file ~/.config/postgresql/docker-compose.yaml run --interactive --rm --tty postgres psql"
