alias wecoachdb="psql --host wecoach.cpq82ioic0rr.ap-south-1.rds.amazonaws.com --port 5432 --user postgres --dbname postgres --password"
alias cna="npx create-next-app --typescript --tailwind --eslint --app --use-yarn"
alias yd="yarn lint && yarn format && yarn build && yarn dev"
alias kubectl="microk8s kubectl"
alias helm="microk8s helm"
